// AQI monitoring stations data
export const STATIONS = [
  {
    station_id: 18,
    station_name: "Anuppur",
    station_let: "23.138013",
    station_long: "81.699238",
    arealocation: "Collectorate",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 22,
    station_name: "Betul ",
    station_let: "21.908980",
    station_long: "77.902435",
    arealocation: "Collector Office",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 27,
    station_name: "Bhopal",
    station_let: "23.210553",
    station_long: "77.425546",
    arealocation: "Paryavaran Parisar",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 34,
    station_name: "Bhopal",
    station_let: "23.265097",
    station_long: "77.381434",
    arealocation: "Collectorate Office",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 10,
    station_name: "Bhopal",
    station_let: "23.233956",
    station_long: "77.399889",
    arealocation: "T T Nagar",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 44,
    station_name: "CTSDF",
    station_let: "22.6294539",
    station_long: "75.6800229",
    arealocation: "Pithampur",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 7,
    station_name: "Damoh",
    station_let: "23.838502",
    station_long: "79.441927",
    arealocation: "Shrivastav Colony",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 23,
    station_name: "Dewas",
    station_let: "22.962205",
    station_long: "76.047959",
    arealocation: "Govt. MG Hospital",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 3,
    station_name: "Dewas",
    station_let: "22.968264",
    station_long: "76.064121",
    arealocation: "Bhopal Chauraha",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 16,
    station_name: "Gwalior",
    station_let: "26.210423",
    station_long: "78.169320",
    arealocation: "Phool Bagh",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 29,
    station_name: "Gwalior",
    station_let: "26.200049",
    station_long: "78.146671",
    arealocation: "Maharaj bada",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 30,
    station_name: "Gwalior",
    station_let: "26.258327",
    station_long: "78.216799",
    arealocation: "DD Nagar",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 15,
    station_name: "Gwalior",
    station_let: "26.202038",
    station_long: "78.198143",
    arealocation: "City Center",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 31,
    station_name: "Indore",
    station_let: "22.76726",
    station_long: "75.88710\r\n",
    arealocation: "Vijay Nagar",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 36,
    station_name: "Indore",
    station_let: "22.752431",
    station_long: "75.884514",
    arealocation: "Maguda Nagar",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 35,
    station_name: "Indore",
    station_let: "22.726042",
    station_long: "75.804831",
    arealocation: "Airport Area",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 37,
    station_name: "Indore",
    station_let: "22.677580",
    station_long: "75.855894",
    arealocation: "Regional Park N Nigam",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 40,
    station_name: "Indore",
    station_let: "22.735083\r\n",
    station_long: "75.855700\r\n",
    arealocation: "Pologround ",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 38,
    station_name: "Indore",
    station_let: "22.703845",
    station_long: "75.886472",
    arealocation: "Residency Area",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 33,
    station_name: "Indore",
    station_let: "22.680019",
    station_long: "75.859093\r\n",
    arealocation: "Regional Park",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 13,
    station_name: "Indore",
    station_let: "22.719217",
    station_long: "75.869601",
    arealocation: "Chhoti Gwaltoli",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 41,
    station_name: "Jabalpur",
    station_let: "23.142932",
    station_long: "79.916147",
    arealocation: "Gupteshwar",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 12,
    station_name: "Jabalpur",
    station_let: "23.165668",
    station_long: "79.932855",
    arealocation: "Marhatal",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 42,
    station_name: "Jabalpur",
    station_let: "23.163252",
    station_long: "79.973050",
    arealocation: "Govindh Bhavan Colony",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 43,
    station_name: "Jabalpur",
    station_let: "23.218184",
    station_long: "79.957770",
    arealocation: "Suhagi",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 11,
    station_name: "Katni",
    station_let: "23.834202",
    station_long: "80.390115",
    arealocation: "Gole Bazar",
    establishedby: "MPPCB",
    nonatn: null,
  },
  {
    station_id: 19,
    station_name: "Katni",
    station_let: "23.806303",
    station_long: "80.372305",
    arealocation: "Regional Office",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 32,
    station_name: "Khandwa",
    station_let: "21.821707",
    station_long: "76.352166",
    arealocation: "Lok Seva Kendra",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 25,
    station_name: "Khargone",
    station_let: "21.830452",
    station_long: "75.617630",
    arealocation: "Nagar Palika",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 8,
    station_name: "Maihar ",
    station_let: "24.261279",
    station_long: "80.723177",
    arealocation: "Sharda Temple",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 5,
    station_name: "Mandideep",
    station_let: "23.108440",
    station_long: "77.511428",
    arealocation: "Sector New Industrial Area",
    establishedby: "MPPCB",
    nonatn: null,
  },
  {
    station_id: 26,
    station_name: "Narsinghpur",
    station_let: "22.943514",
    station_long: "79.188508",
    arealocation: "District Education Office",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 17,
    station_name: "Neemuch",
    station_let: "24.460708",
    station_long: "74.875915",
    arealocation: "Civil Hospital",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 39,
    station_name: "Panna",
    station_let: "24.735896",
    station_long: "80.194095",
    arealocation: "Collectorate",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 1,
    station_name: "Pithampur",
    station_let: "22.624758",
    station_long: "75.675238",
    arealocation: "Sector-2 Industrial Area",
    establishedby: "MPPCB",
    nonatn: null,
  },
  {
    station_id: 9,
    station_name: "Ratlam",
    station_let: "23.334094",
    station_long: "75.037136",
    arealocation: "Shathri Nagar",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 20,
    station_name: "Rewa",
    station_let: "24.54663",
    station_long: "81.32058",
    arealocation: "Regional Office",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 21,
    station_name: "Rewa",
    station_let: "24.53869",
    station_long: "81.28911",
    arealocation: "Collector Office",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 28,
    station_name: "Sagar",
    station_let: "23.838807",
    station_long: "78.758577",
    arealocation: "Collectorate Office",
    establishedby: "MPPCB",
    nonatn: true,
  },
  {
    station_id: 14,
    station_name: "Sagar",
    station_let: "23.864633",
    station_long: "78.897981",
    arealocation: "Deen Dayal Nagar",
    establishedby: null,
    nonatn: true,
  },
  {
    station_id: 6,
    station_name: "Satna",
    station_let: "24.602160",
    station_long: "80.832589",
    arealocation: "Bandhavgar Colony",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 4,
    station_name: "Singrauli",
    station_let: "24.108970",
    station_long: "82.64580",
    arealocation: "Surya Kiran Bhawan Dudhichua",
    establishedby: "MPPCB",
    nonatn: false,
  },
  {
    station_id: 24,
    station_name: "Singrauli",
    station_let: "24.071713",
    station_long: "82.618340",
    arealocation: "Trauma Centre Waidhan",
    establishedby: null,
    nonatn: null,
  },
  {
    station_id: 2,
    station_name: "Ujjain",
    station_let: "23.18270",
    station_long: "75.76819",
    arealocation: "Mahakaleshwar Temple",
    establishedby: "MPPCB",
    nonatn: true,
  },
];

// Helper function to get stations within a certain radius of a location
export const getStationsWithinRadius = (
  centerLat,
  centerLng,
  radiusKm = 50
) => {
  const toRadians = (degrees) => degrees * (Math.PI / 180);
  const toDegrees = (radians) => radians * (180 / Math.PI);

  const calculateDistance = (lat1, lon1, lat2, lon2) => {
    const R = 6371; // Earth's radius in kilometers
    const dLat = toRadians(lat2 - lat1);
    const dLon = toRadians(lon2 - lon1);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(toRadians(lat1)) *
        Math.cos(toRadians(lat2)) *
        Math.sin(dLon / 2) *
        Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c;
  };

  return STATIONS.filter((station) => {
    const lat = parseFloat(station.station_let);
    const lng = parseFloat(station.station_long.replace(/\r\n/g, ""));
    const distance = calculateDistance(centerLat, centerLng, lat, lng);
    return distance <= radiusKm;
  });
};

// Helper function to clean station coordinates (remove carriage returns)
export const getCleanStationCoordinates = (station) => {
  return {
    latitude: parseFloat(station.station_let),
    longitude: parseFloat(station.station_long.replace(/\r\n/g, "")),
  };
};
